// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAinvXGz434_ZKSQeD5vGqn_X4H1Aepm8Y',
    appId: '1:759968422892:web:c061eaf40cfdf0cfe87ec9',
    messagingSenderId: '759968422892',
    projectId: 'pitbi-archive',
    authDomain: 'pitbi-archive.firebaseapp.com',
    storageBucket: 'pitbi-archive.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvaVEgfGb3zLFQJfq_ZrK3408RRKB_944',
    appId: '1:759968422892:android:b38932cad4de38a0e87ec9',
    messagingSenderId: '759968422892',
    projectId: 'pitbi-archive',
    storageBucket: 'pitbi-archive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5gSb3Y8jKqBJW63NeqcyrXsfKxcgb0Aw',
    appId: '1:759968422892:ios:19f1abaf18dfc63ee87ec9',
    messagingSenderId: '759968422892',
    projectId: 'pitbi-archive',
    storageBucket: 'pitbi-archive.appspot.com',
    iosBundleId: 'com.example.pitbiarhive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5gSb3Y8jKqBJW63NeqcyrXsfKxcgb0Aw',
    appId: '1:759968422892:ios:6fc076226697c3b7e87ec9',
    messagingSenderId: '759968422892',
    projectId: 'pitbi-archive',
    storageBucket: 'pitbi-archive.appspot.com',
    iosBundleId: 'com.example.pitbiarhive.RunnerTests',
  );
}
